### ISSUE TITLE
Module repository issues on Arch-based distros

### ISSUE THREAD

**Issue by KieranChandler** [PowerShell/PowerShell-Snap#40]
When installing the powershell package via snap on Ubuntu the default repository is registered out of the box and modules can be installed. When installing on an Arch-based distro however, no repository is present. In addition no repository is added when adding the default repository via
`Register-PSRepository -Default`

This results in the following error when trying to install modules:
```
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'AWSPowershell.NetCore'. Try Get-PSRepository to see all available registered module repositories.
At /var/lib/snapd/snap/powershell/39/opt/powershell/Modules/PowerShellGet/PSModule.psm1:9508 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by TravisEz13** [comment]
I've not been able to reproduce this issue.  I need a VM image or detail instructions for creating the repro environment.

**Comment by TravisEz13** [comment]
no response for months.  Closing until further details are supplied.
