### ISSUE TITLE
 Unable to start PowerShell | openSUSE Tumbleweed

### ISSUE THREAD

**Issue by bkaczynski** [PowerShell/PowerShell-Snap#56]
I've installed PoweShell using commands from [THIS SITE](https://snapcraft.io/install/powershell/opensuse) and after that I receive this error when I try to run pwsh
> ~> pwsh
Failed to load �V, error: /snap/powershell/104/opt/powershell/../../lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
Failed to bind to CoreCLR at '/snap/powershell/104/opt/powershell/'
Failed to create CoreCLR, HRESULT: 0x80008088

**Comment by TravisEz13** [comment]
dup of #65
