### ISSUE TITLE
Enter-PSSession: SPNEGO cannot find mechanisms to negotiate

### ISSUE THREAD

**Issue by Himura2la** [PowerShell/PowerShell-Snap#69]
According to this, it's required to add a `gss-ntlmssp` package

https://github.com/PowerShell/PowerShell/issues/6647#issuecomment-632613488

**Comment by Himura2la** [comment]
@TravisEz13, ping

**Comment by TravisEz13** [comment]
This is not going to work in the snap.  It relies on libraries that aren't maintained and load other libraries by hard coded paths.  This won't work in a snap.

See https://github.com/PowerShell/PowerShell-Snap#known-issues
