### ISSUE TITLE
Ubuntu 21.04 both powershell and powershell-preview fail to start

### ISSUE THREAD

**Issue by Lockszmith-GH** [PowerShell/PowerShell-Snap#75]
Fresh installation of Ubuntu Hirsute Hippo, after installing `powershell` or `powershell-preview` attempting to run `pwsh` (or `pwsh-preview`) attempt to load the shell but fails with:
```
❯ pwsh-preview
PowerShell 7.2.0-preview.7
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell                                                                                                                               │
Type 'help' to get help.

PS /home/user> No usable version of libssl was found
zsh: IOT instruction (core dumped)  pwsh-preview
```

anyway to know what library version it's looking for and if there is a dependency that isn't automatically detected/installer?

**Comment by Sprbb** [comment]
pwsh-preview
PowerShell 7.2.0-preview.9
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/bas> No usable version of libssl was found
Aborted (core dumped)
