### ISSUE TITLE
Please upgrade to `base: core20`

### ISSUE THREAD

**Issue by xnox** [PowerShell/PowerShell-Snap#87]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

`base: core18` is now discouraged with all server snaps having moved onto `base: core20`.

it will give you access to a newer, Ubuntu 20.04 LTS based runtime, and will minimise install size for end-users, as they will no longer need to pull in core18 whenever they want to use powershell.

### Expected behavior

```console
$ snap info --verbose powershell | grep base:
base: core20
```

### Actual behavior

```console
$ snap info --verbose powershell | grep base:
base: core18
```

### Environment data

```PowerShell
I am running Ubuntu
```

### Version

latest/stable

**Comment by anamnavi** [comment]
@diddledani Thanks for this thorough explanation, I'm still quite new to this project so this context helps! I've updated the PR description to reflect this. As for the suggestion of upgrading to core22 I'll discuss this with the team and update the PR. Thanks!

**Comment by anamnavi** [comment]
Closing at this is available via stable and preview now, thanks!
