### ISSUE TITLE
All channels of preview snap package except latest/stable are old.

### ISSUE THREAD

**Issue by rokejulianlockhart** [PowerShell/PowerShell-Snap#97]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
`snap install powershell-preview` + (`--channel=latest/edge` or `--channel=latest/beta` or `--channel=latest/candidate`).

### Expected behavior
All should at least provide the same version. Edge should probably compile directly from `git`. Either that, or remove the channels.

### Actual behavior
![image](https://user-images.githubusercontent.com/42837531/215923946-c23ae60e-0ba7-45dc-993f-b7780f0ff782.png)

**Comment by rokejulianlockhart** [comment]
@TravisEz13, in which case, disable the channels.

This definitely isn't a question. It's a bug report.

**Comment by rokejulianlockhart** [comment]
@TravisEz13, why are they unable to be disabled? Other listings have disabled them.

**Comment by TravisEz13** [comment]
Because the feature doesn't exist.  I can close a channel, which is temporary.  Please use stable.
